# Change these first
owner: lunar-d # Your GitHub organization or username, where this repository lives
repo: StatusLunardreams # The name of this repository

sites:
  - name: LunarDreams (Domaine Principale)
    url: https://lunardreams.fr
    assignees:
      - lunar-d
  - name: Dnydns
    url: https://lunardreams.duckdns.org/
    __dangerous__insecure: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.lunardreams.fr
  # baseUrl: /your-repo-name
  name: Upptime | Lunardreams.fr
  theme: dark
  themeUrl: https://status.lunardreams.fr/custom-theme.css
  logoUrl: https://status.lunardreams.fr/logo.png
  # Etat des services disponibles sur lunardreams.fr alimenté par Upptime.
  # Si l'un des services ne réponds pas merci de me contacter sur GitHub ou par mail.
  introTitle: "Etats des services disponibles sur [**lunardreams.fr**](https://lunardreams.fr) alimenté par [Upptime](https://github.com/upptime/upptime)."
  introMessage: "Si l'un des services ne réponds pas merci de me contacter sur Discord ou par mail."
  navbar:
    - title: Status
      href: /
    - title: LunarDreams
      href: https://lunardreams.fr
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
  metaTags:
    - name: "robots"
      content: "noindex"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
